
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nexa_client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nexa_server
    ports:
      - "8000:8000"
